name: mona_coffee
description: "Your personal guide to discovering the perfect coffee."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.4.4
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  logger: ^2.4.0
  http: ^1.2.2
  intl: ^0.20.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800
  assets:
    - assets/icons/
    - assets/images/
